services:
  - type: web
    name: daoresorts-app
    env: node
    rootDir: "backend server"
    buildCommand: npm install && npm run build
    startCommand: npm start
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
